import assert from 'node:assert/strict';
import test from 'node:test';
import { soundDefaults as defaults, rawSoundVolume as raw, validateSoundConfig as valid, soundPresentation as p } from '../ui/view-model.js';
test('defaults valid',()=>assert.equal(valid(defaults()).enabled,true));
test('independent default objects',()=>{const a=defaults(),b=defaults();a.error.volume=1;assert.equal(b.error.volume,80);});
test('working disabled',()=>assert.equal(defaults().working.enabled,false));
test('waiting defaults',()=>{const r=defaults().waiting;assert.equal(r.mode,'double');assert.equal(r.delay_seconds,2);assert.equal(r.interval_seconds,15);assert.equal(r.limit.seconds,180);});
test('error defaults',()=>assert.deepEqual(defaults().error,{enabled:true,mode:'triple',volume:80,delay_seconds:3,interval_seconds:10,limit:{kind:'duration',seconds:120}}));
test('done defaults separate from 300s light timer',()=>assert.equal(defaults().done.limit.seconds,30));
test('full volume never writes 100',()=>assert.equal(raw(100),50));
test('zero is silent',()=>assert.equal(raw(0),0));
test('all levels are bounded',()=>{for(let n=0;n<=100;n++)assert.ok(raw(n)<=50);});
test('reject invalid volume',()=>{for(const n of [-1,101,NaN,12.5,'50'])assert.throws(()=>raw(n));});
test('inherited volume valid',()=>assert.equal(valid(defaults()).waiting.volume,null));
test('delay bounds',()=>{const c=defaults();c.error.delay_seconds=301;assert.throws(()=>valid(c));});
test('interval bounds',()=>{const c=defaults();c.error.interval_seconds=4;assert.throws(()=>valid(c));});
test('count bounds',()=>{const c=defaults();c.error.limit={kind:'count',count:0};assert.throws(()=>valid(c));});
test('duration bounds',()=>{const c=defaults();c.error.limit={kind:'duration',seconds:1};assert.throws(()=>valid(c));});
test('once valid',()=>{const c=defaults();c.done.limit={kind:'once'};valid(c);});
test('until state valid',()=>{const c=defaults();c.waiting.limit={kind:'until_state'};valid(c);});
test('unknown limit rejected',()=>{const c=defaults();c.done.limit={kind:'forever_raw'};assert.throws(()=>valid(c));});
test('missing status not safe',()=>assert.equal(p().canTest,false));
test('low battery guard',()=>{const v=p({status:'low',gate:'low',low_battery:true,can_test:false});assert.equal(v.low,true);assert.match(v.title,/低电量/);assert.equal(v.canTest,false);});
test('recovery is not ready',()=>{const v=p({status:'recovering',gate:'recovering',low_battery:true});assert.equal(v.ready,false);assert.match(v.guard,/两次/);});
test('countdown uses backend deadline',()=>assert.equal(p({status:'scheduled',next_ms:20000},8000).next,'00:12'));
test('master off label',()=>assert.equal(p({status:'disabled'}).title,'蜂鸣已关闭'));
test('muted does not show endless countdown',()=>assert.equal(p({status:'quiet',until_ms:999999},0).until,''));
test('success rounds are not task count',()=>assert.equal(p({status:'scheduled',sent_rounds:3}).rounds,'3 轮已发送'));
